nombre = input("Ingrese su nombre completo: ")
edad = int(input("Ingrese su edad: "))
estatura = float(input("Ponga su estatura: "))
peso = float(input("Ponga su peso: "))
direccion = input("Coloque su direccion: ")
num_telefono = input("Colaque su numero telefonico: ")
print("La informacion ingresada es la siguiente:")
print(f"Nombre completo: {nombre}")
print(f"Edad: {edad}")
print (f"Estatura: {estatura}cm")
print(f"Peso: {peso}Kg")
print(f"Direccion: {direccion}")
print(f"Numero de telefono: {num_telefono}")