radio = float(input("Ponga el radio de un circulo y le dare los datos del circulo: "))
diametro = float (2 * radio)
circunferencia = float(2 * 3.14159 * radio )
area = float(3.14159 * radio ** 2)
print(f"Su diametro: {diametro},  Su circunferencia: {circunferencia},  Su area: {area}")